/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32H743xx.h"
#include "irqDriver.h"
#include "gpioDriver.h"

GPIOx_Confg_t gpioB;

int main(void) {

	RCC_Reg_t rcc;
	initializeRCC(&rcc);
	enableSYSCFG(&rcc, ENABLE);
	enableGPIOx(&rcc, GPIOC, ENABLE);
	enableGPIOx(&rcc, GPIOB, ENABLE);

	//GPIOx_Confg_t gpioB;
	initializeGPIOx(&gpioB, GPIOB_BASEADDR);
	setGPIOxModer(&gpioB, PIN_0, MODE_OUTPUT);
	setGPIOxType(&gpioB, PIN_0, TYPE_PUSH_PULL);
	setGPIOxResistor(&gpioB, PIN_0, PUPD_UP);
	setGPIOxOutput(&gpioB, PIN_0, HIGH);

	GPIOx_Confg_t gpioC;
	initializeGPIOx(&gpioC, GPIOC_BASEADDR);
	setGPIOxModer(&gpioC, PIN_13, MODE_INPUT);
	setGPIOxResistor(&gpioC, PIN_13, PUPD_DOWN);

	SYSCFG_Reg_t syscfg;
	setEXTI_CR(&syscfg, PIN_13, GPIOC);

	EXTI_Reg_t exti;
	setRTSR(&exti, PIN_13, ENABLE);
	enableCPUIMRx(&exti, IMR1, PIN_13, ENABLE);

	enableIRQ(40, TRUE);
	//setIRQPenReg(40, TRUE);

	while (1) {
		/*
		 if (getGPIOxState(&gpioC, PIN_13)) {
		 setGPIOxOutput(&gpioB, PIN_0, HIGH);
		 //enableIRQ(40, TRUE);
		 //setIRQPenReg(40, TRUE);
		 } else {
		 setGPIOxOutput(&gpioB, PIN_0, LOW);
		 }
		 */
	}
}

void EXTI0_IRQHandler(void) {
	boolean teste = FALSE;
	teste = TRUE;
	setIRQPenReg(6, teste);
}
void WWDG1_IRQHandler(void) {
	boolean teste = FALSE;
	teste = TRUE;
	setIRQPenReg(0, teste);
}

void EXTI15_10_IRQHandler(void) {
	EXTI_Reg_t exti;

	boolean pinState = getGPIOxState(&gpioB, PIN_0);
	if (pinState) {
		setGPIOxOutput(&gpioB, PIN_0, LOW);
	} else {
		setGPIOxOutput(&gpioB, PIN_0, HIGH);
	}
	setCPUIPRx(&exti, 0, PIN_13, DISABLE);

}
